name: DEPLOY ON PULL REQUEST

on:
  pull_request:
    branches:
      - stage

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: true 

      - name: Update submodules
        run: |
          echo "Updating submodules"
          git submodule update --init --recursive --remote
          echo "DEPLOYING TO STAGE"


     
